name: "Trigger Hightouch Sync"
description: "This action asynchronously triggers a Hightouch sync based on a sync ID."
branding:
  icon: "refresh-ccw"
  color: "green"
inputs:
  sync-id:
    description: "The ID of the sync you wish to trigger"
    required: true
runs:
  using: composite
  steps:
    - name: Check for valid API key
      shell: bash
      id: check-api-key
      if: env.HIGHTOUCH_API_KEY == 0
      run: exit 1
    - name: Trigger sync via Hightouch API
      shell: bash
      id: trigger-sync
      if: inputs.sync-id
      run: |
        curl --location --fail -g --request POST 'https://api.hightouch.com/api/v1/syncs/${{ inputs.sync-id }}/trigger' --header 'Authorization: Bearer ${{ env.HIGHTOUCH_API_KEY }}'

# TODO - Add polling step to check if sync succeeded
